# The URL the site will be built for
base_url = "https://satler.dev/"
default_language = "ja"
generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Theme for the site
theme = "anemone"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
render_emoji = true
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_links_target_blank = true
smart_punctuation = true
lazy_async_image = true

[extra]
# favicon
svg_favicon = true
default_card_image = "favicon.png"
favicon = "favicon.svg"
twitter_id = "satleri_sentler"
toc = true

list_pages = true

author = "satler"
display_author = true

default_theme = "dark"
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_ja = "/home/" },
  # { url = "/ja", name_en = "/ja/", name_ja = "" },
  # { url = "/", name_ja = "/en/", name_en = "" },
  { url = "/product", name_en = "/product/", name_ja = "/product/" },
  { url = "/blog", name_en = "/blog/", name_ja = "/blog/" }
]
