[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
xflags = "0.3.2"
xshell = "0.2.7"

[dependencies.chrono]
version = "0.4.39"
default-features = false
features = ["now", "std", "alloc"]
